repos:
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v3.7.1  # MUST match your pre-commit version
    hooks:
      - id: sub-pre-commit
        alias: backend
        name: "pre-commit for backend/"
        args: ["-p", "backend/"]
        files: "^backend/.*"
        stages: ["commit"]
      - id: sub-pre-commit
        alias: frontend
        name: "pre-commit for frontend"
        args: ["-p", "frontend"]
        files: "^frontend/.*"
        stages: ["commit"]
