version: "3"

services:

  addon-dev:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.acceptance
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION}
    volumes:
      - .:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
      HOST: 0.0.0.0
    ports:
      - 3000:3000
      - 3001:3001
    tty: true
    depends_on:
      - backend-acceptance
    profiles:
      - dev

  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    image: plone/plone-backend:6.0.7
    command: ["/app/bin/robot-server", "plone.app.robotframework.testing.PLONE_ROBOT_TESTING"]
    environment:
      ZSERVER_HOST: "0.0.0.0"
      ZSERVER_PORT: "55001"
      LISTEN_PORT: "55001"
      CONFIGURE_PACKAGES: "plone.restapi,plone.volto"
      APPLY_PROFILES: "plone.volto:default-homepage"
      ADDONS: "plone.app.robotframework plone.volto"
    ports:
      - 55001:55001
      - 8080:8080
    profiles:
      - dev
      - prod
